server:
  port: 8091
  
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8090/oauth/token
      userAuthorizationUri: http://localhost:8090/oauth/authorize
      clientId: theClient
      clientSecret: thisissecret
    resource:
      userInfoUri: http://localhost:8090/user